### ISSUE TITLE
Aliexpress Oauth docs

### ISSUE THREAD

**Issue by scythargon** [pupi94/omniauth-aliexpress-oauth2#1]
Hello! I've stumbled upon your library and even though I need this functionality in Python - can you please tell me where did you find Aliexpress Oauth and API docs at all? 
Thank you!

**Comment by pupi94** [comment]
> Hello! I've stumbled upon your library and even though I need this functionality in Python - can you please tell me where did you find Aliexpress Oauth and API docs at all?
> Thank you!

https://developers.aliexpress.com/doc.htm?docId=107726&docType=1

**Comment by scythargon** [comment]
@pupi94 Thanks a lot! It's hard to go through that documentation even with Google Translate, can you please tell me if after the authorization I'll be able to get a list of user's orders along with the tracking information?

**Comment by pupi94** [comment]
> @pupi94 Thanks a lot! It's hard to go through that documentation even with Google Translate, can you please tell me if after the authorization I'll be able to get a list of user's orders along with the tracking information?
Sorry, I should send you the document in English：
https://developers.aliexpress.com/en/doc.htm?docId=108969&docType=1

**Comment by pupi94** [comment]
> @pupi94 Thanks a lot! It's hard to go through that documentation even with Google Translate, can you please tell me if after the authorization I'll be able to get a list of user's orders along with the tracking information?
First, you should register a developer account and create a APP, but I'm not sure which app of aliexpress you want to use.

We only use Drop Shipping related functions, and use Drop Shipping API get orders and tracking information after the authorization

**Comment by pupi94** [comment]
> @pupi94 Thanks a lot! It's hard to go through that documentation even with Google Translate, can you please tell me if after the authorization I'll be able to get a list of user's orders along with the tracking information?

First, you should register a developer account and create a APP, but I'm not sure which app of aliexpress you want to use.

We only use Drop Shipping related functions, and use Drop Shipping API get orders and tracking information after the authorization
